//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibClientConsole.VelibServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServices.IVelibServices")]
    public interface IVelibServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetStationsInCity", ReplyAction="http://tempuri.org/IVelibServices/GetStationsInCityResponse")]
        string GetStationsInCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetStationsInCity", ReplyAction="http://tempuri.org/IVelibServices/GetStationsInCityResponse")]
        System.Threading.Tasks.Task<string> GetStationsInCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetAvailableVelibsInStation", ReplyAction="http://tempuri.org/IVelibServices/GetAvailableVelibsInStationResponse")]
        string GetAvailableVelibsInStation(string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetAvailableVelibsInStation", ReplyAction="http://tempuri.org/IVelibServices/GetAvailableVelibsInStationResponse")]
        System.Threading.Tasks.Task<string> GetAvailableVelibsInStationAsync(string station);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServicesChannel : VelibClientConsole.VelibServices.IVelibServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServicesClient : System.ServiceModel.ClientBase<VelibClientConsole.VelibServices.IVelibServices>, VelibClientConsole.VelibServices.IVelibServices {
        
        public VelibServicesClient() {
        }
        
        public VelibServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStationsInCity(string city) {
            return base.Channel.GetStationsInCity(city);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsInCityAsync(string city) {
            return base.Channel.GetStationsInCityAsync(city);
        }
        
        public string GetAvailableVelibsInStation(string station) {
            return base.Channel.GetAvailableVelibsInStation(station);
        }
        
        public System.Threading.Tasks.Task<string> GetAvailableVelibsInStationAsync(string station) {
            return base.Channel.GetAvailableVelibsInStationAsync(station);
        }
    }
}
