//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibServerGui.VelibServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServices.IVelibServices")]
    public interface IVelibServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetStationsInCity", ReplyAction="http://tempuri.org/IVelibServices/GetStationsInCityResponse")]
        VelibLibrary.Station[] GetStationsInCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetStationsInCity", ReplyAction="http://tempuri.org/IVelibServices/GetStationsInCityResponse")]
        System.Threading.Tasks.Task<VelibLibrary.Station[]> GetStationsInCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetAvailableVelibsInStation", ReplyAction="http://tempuri.org/IVelibServices/GetAvailableVelibsInStationResponse")]
        VelibLibrary.Station GetAvailableVelibsInStation(string city, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServices/GetAvailableVelibsInStation", ReplyAction="http://tempuri.org/IVelibServices/GetAvailableVelibsInStationResponse")]
        System.Threading.Tasks.Task<VelibLibrary.Station> GetAvailableVelibsInStationAsync(string city, string station);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServicesChannel : VelibServerGui.VelibServices.IVelibServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServicesClient : System.ServiceModel.ClientBase<VelibServerGui.VelibServices.IVelibServices>, VelibServerGui.VelibServices.IVelibServices {
        
        public VelibServicesClient() {
        }
        
        public VelibServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VelibLibrary.Station[] GetStationsInCity(string city) {
            return base.Channel.GetStationsInCity(city);
        }
        
        public System.Threading.Tasks.Task<VelibLibrary.Station[]> GetStationsInCityAsync(string city) {
            return base.Channel.GetStationsInCityAsync(city);
        }
        
        public VelibLibrary.Station GetAvailableVelibsInStation(string city, string station) {
            return base.Channel.GetAvailableVelibsInStation(city, station);
        }
        
        public System.Threading.Tasks.Task<VelibLibrary.Station> GetAvailableVelibsInStationAsync(string city, string station) {
            return base.Channel.GetAvailableVelibsInStationAsync(city, station);
        }
    }
}
